annotations:
  catalog.cattle.io/certified: playcekube
  catalog.cattle.io/namespace: playcekube-dev
  catalog.cattle.io/release-name: harbor
  category: Infrastructure
apiVersion: v2
appVersion: 2.5.2
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.x.x
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 1.x.x
description: Harbor is an open source trusted cloud-native registry to store, sign,
  and scan content. It adds functionalities like security, identity, and management
  to the open source Docker distribution.
home: https://github.com/bitnami/charts/tree/master/bitnami/harbor
icon: https://raw.githubusercontent.com/OpenSourceConsulting/playcekube-charts/v2.1.0/assets/icon/harbor-icon.png
keywords:
- develops
- docker
- registry
- vulnerability
- scan
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: harbor
sources:
- https://github.com/bitnami/bitnami-docker-harbor-core
- https://github.com/bitnami/bitnami-docker-harbor-portal
- https://github.com/bitnami/bitnami-docker-harbor-jobservice
- https://github.com/bitnami/bitnami-docker-harbor-registry
- https://github.com/bitnami/bitnami-docker-harbor-registryctl
- https://goharbor.io/
version: 14.0.3
