annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Allow probes to be turned off completly (this is not advised unless you know what you're doing)."
  catalog.cattle.io/certified: playcekube
  catalog.cattle.io/namespace: kube-system
  catalog.cattle.io/release-name: metrics-server
apiVersion: v2
appVersion: 0.6.1
description: Metrics Server is a scalable, efficient source of container resource
  metrics for Kubernetes built-in autoscaling pipelines.
home: https://github.com/kubernetes-sigs/metrics-server
icon: https://raw.githubusercontent.com/OpenSourceConsulting/playcekube-charts/v2.1.0/assets/icon/metrics-server-icon.icon
keywords:
- monitoring
- infrastructure
- kubernetes
- metrics-server
- metrics
maintainers:
- name: stevehipwell
  url: https://github.com/stevehipwell
- name: krmichel
  url: https://github.com/krmichel
- name: endrec
  url: https://github.com/endrec
name: metrics-server
sources:
- https://github.com/kubernetes-sigs/metrics-server
type: application
version: 3.8.2
