---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: {{.Values.namespace}}
  name: proxy-admin-viz
  labels:
    linkerd.io/extension: viz
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  podSelector:
    matchLabels:
      linkerd.io/extension: viz
  port: linkerd-admin
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: {{.Values.namespace}}
  name: proxy-admin-viz
  labels:
    linkerd.io/extension: viz
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  server:
    name: proxy-admin-viz
  client:
    # for kubelet probes
    unauthenticated: true

