annotations:
  artifacthub.io/changes: |
    - [Changed]: Update redis-ha dependency for better configuration options
  catalog.cattle.io/certified: playcekube
  catalog.cattle.io/namespace: playcekube-dev
  catalog.cattle.io/release-name: argo-cd
apiVersion: v2
appVersion: v2.4.3
dependencies:
- condition: redis-ha.enabled
  name: redis-ha
  repository: https://dandydeveloper.github.io/charts/
  version: 4.17.1
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool
  for Kubernetes.
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/OpenSourceConsulting/playcekube-charts/v2.1.0/assets/icon/argo-cd-icon.png
keywords:
- develops
- argoproj
- argocd
- gitops
maintainers:
- name: alexec
- name: alexmt
- name: jessesuen
- name: seanson
name: argo-cd
version: 4.9.11
