annotations:
  catalog.cattle.io/certified: playcekube
  catalog.cattle.io/namespace: playcekube
  catalog.cattle.io/release-name: keycloak
  category: DeveloperTools
  images: |
    - name: keycloak-config-cli
      image: docker.io/bitnami/keycloak-config-cli:5.10.0-debian-11-r0
    - name: keycloak
      image: docker.io/bitnami/keycloak:23.0.4-debian-11-r0
  licenses: Apache-2.0
apiVersion: v2
appVersion: 23.0.4
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Keycloak is a high performance Java-based identity and access management
  solution. It lets developers add an authentication layer to their applications with
  minimum effort.
home: https://bitnami.com
icon: https://raw.githubusercontent.com/OpenSourceConsulting/playcekube-charts/v2.1.0/assets/icon/keycloak-icon.png
keywords:
- security
- infrastructure
- keycloak
- access-management
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: keycloak
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/keycloak
version: 18.1.0
