annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Added Gloo Platform provider RBAC rules
  artifacthub.io/signKey: |
    fingerprint: 2B8F22F57260EFA67BE1C5824B11F800CD9D2252
    url: https://argoproj.github.io/argo-helm/pgp_keys.asc
  catalog.cattle.io/certified: playcekube
  catalog.cattle.io/namespace: playcekube-dev
  catalog.cattle.io/release-name: argo-rollouts
apiVersion: v2
appVersion: v1.6.4
description: A Helm chart for Argo Rollouts
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/OpenSourceConsulting/playcekube-charts/v2.1.0/assets/icon/argo-rollouts-icon.png
keywords:
- develops
- argoproj
- argo-rollouts
maintainers:
- name: argoproj
  url: https://argoproj.github.io/
name: argo-rollouts
sources:
- https://github.com/argoproj/argo-rollouts
version: 2.34.1
